# Generated by Django 6.1 on 2026-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole / Road Damage'), ('streetlight', 'Broken Streetlight'), ('garbage', 'Garbage / Waste'), ('water', 'Water Leakage'), ('drainage', 'Drainage Problem'), ('infrastructure', 'Damaged Public Infrastructure'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('assigned', 'Department Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
