# Generated by Django 6.1 on 2026-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity Department'), ('roads', 'Roads & Infrastructure Department'), ('sanitation', 'Sanitation Department'), ('water', 'Water Department'), ('drainage', 'Drainage Department'), ('municipal', 'Municipal Department'), ('other', 'Other Department')], max_length=50, null=True),
        ),
    ]
